spring:
  application:
    name: ms-catalogo-service
  profiles:
    active: development
  config:
      import: optional:config server:http://root:123456@localhost:7070
  cloud:
    config:
      enabled: false